return {
	s(
		{
			trig = "conf",
			snippetType = "snippet",
			desc = "Basic setup for conf doc w/ code snippets",
			trigEngine = "plain",
		},
		t({
			"#let conf(doc, doctitle: []) = {",

			"  // SET RULES //////////////////",

			'  set heading(numbering: "1.1")',
			"  set document(",
			"    title: doctitle,",
			'     author: "Frederik L. K. Nørregaard",',
			"    keywords: (),",
			"  )",

			"  // SHOW RULES /////////////////",

			"  //Page setup",
			"  set page(",
			'    paper: "a4",',
			"    header: align(right, context document.title),",
			'    numbering: "1",',
			"  )",
			"  title()",
			"  doc",
			"}",
			"",
			"// Code snippets as figures",
			'#let code_snippet(lang: "", code: "", caption: none, label: none) = {',
			"  let fig = figure(",
			"    align(left, block(fill: luma(240), inset: 8pt, radius: 4pt, width: 100%, raw(lang: lang, block: true, code))),",
			"    caption: if caption != none { caption },",
			'	  supplement: "Listing",',
			"    kind: raw,",
			"  )",
			"  if label != none {",
			"// Aligner caption",
			"// show figure.where(kind: raw): it => {",
			"//   it.body",
			"//   align(left, it.caption)",
			"// }",
			"    [#fig#label]",
			"  } else {",
			"    fig",
			"  }",
			"}",
		})
	),

	s(
		{
			trig = "main",
			snippetType = "snippet",
			desc = "Basic setup for blank 1 file report",
			trigEngine = "plain",
		},
		t({
			"#let doctitle = []",
			' #import "conf.typ": code_snippet, conf',
			"",
			"// Show rules",
			"#show: conf.with(doctitle: doctitle)",
			"",
			"// Set rules",
			"#set linebreak(justify: false)",
			"",
			"#grid(",
			"  columns: (auto, auto),",
			"  align: left,",
			"  column-gutter: 1em,",
			"  gutter: 8pt,",
			"  [Author:], [*FREDERIK LAUST KIRCHHOFF NØRREGAARD* #linebreak()],",
			"  [Email:], [*#link()*#linebreak()],",
			")",
			"",
			"#show link: underline",
			" Link to online repository: ",
			"",
			"= Introduction",
		})
	),
}
